### ISSUE TITLE
Kernel panic - Ubuntu 18.04.05 Installation

### ISSUE THREAD

**Issue by CornerStoneF** [up-board/up-community#9]
Hi, 
I wanted to install Ubuntu 18.04 regarding the Wiki-guide, but got an kernel panic error while processing. 
Board: Up Core 01/16 (UPC-CHT01-A20-0116-A11)

See attached error message:
![up_core-kernel](https://user-images.githubusercontent.com/101316971/157609088-3f117d3b-a574-4df5-8919-1c3ace14bc03.jpg)

I created the bootable usb-stick with "balenaEtcher" and the Ubuntu "image creator tool" neither did work.

I hope you can help me. 
Thank you very much.

--
CornerStoneF

**Comment by CammyTetehJr** [comment]
Hi,

Can you try to update the BIOS to latest UCR1BM18 and retry installation of ubuntu. You can find the download link [here](https://downloads.up-community.org/download/up-core-uefi-bios-ucr1bm18/)

**Comment by CornerStoneF** [comment]
Hi, 

thank you. 
Updating the BIOS worked for me to solve this problem.

**Comment by CammyTetehJr** [comment]
Glad to hear that
